name: Publish release to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@latest
        with:
          identifier: LRCLIB.LRCGET
          installers-regex: 'x64_en-US\.msi'
          token: ${{ secrets.WINGET_ACC_TOKEN }}
